### ISSUE TITLE
Bug on Server side

### ISSUE THREAD

**Issue by webgtx** [bubuntoid/YOVPS#13]
If you give a link to the input without timecodes in the description, the server will return an error

**Comment by bubuntoid** [comment]
у меня приходит такая ошибка (она и ожидается если чо)
![image](https://user-images.githubusercontent.com/51204805/127538190-d54beaec-1ce0-4b9a-af61-fb3a801aff7e.png)

**Comment by bubuntoid** [comment]
а с какого метода прилетает 404? или о чом там речь была я уже забыл все...

**Comment by webgtx** [comment]
Я говорил про описание которое под видеом.

**Comment by bubuntoid** [comment]
нужен реальный кейс, можешь кинуть url видоса - что ожидается? - что возвращается по факту?

**Comment by webgtx** [comment]
![Screenshot from 2021-07-30 14-24-10](https://user-images.githubusercontent.com/62614322/127646328-fa163cd0-4735-40c5-a174-e15636d7effb.png)
![Screenshot from 2021-07-30 14-24-39](https://user-images.githubusercontent.com/62614322/127646326-52c0687c-36f7-4ec8-b87b-f11a68052130.png)

А я ожидаю 1 таймкод. Как 1 песню.

**Comment by bubuntoid** [comment]
ну вообще изначально и не планировалось обрабатывать видосы без таймкодов, на это есть другие сервисы, но не вижу препятствий делать так же, может оставим это на следующий релиз?

**Comment by webgtx** [comment]
Сервер перестал присылать фото, предлагаю вместо картинок передавать ссылку на фото прямо из серверов ютуба.
![image](https://user-images.githubusercontent.com/62614322/127754486-2629004b-874b-4411-ad91-c7b0ab50a4f2.png)

**Comment by bubuntoid** [comment]
покажи запрос, и давай к каждой баге/треду сразу прикреплять тестируемый url

**Comment by bubuntoid** [comment]
возможно ты не указал `"includeThumbnails": true`
![image](https://user-images.githubusercontent.com/51204805/127754934-3e7bbfee-b722-433f-a544-52dfccbea1de.png)

**Comment by webgtx** [comment]
![image](https://user-images.githubusercontent.com/62614322/127894586-7a670e98-a7b8-460f-941b-f430dc89b7ae.png)
