### ISSUE TITLE
fe 29.07.2021 remarks

### ISSUE THREAD

**Issue by bubuntoid** [bubuntoid/YOVPS#14]
![image](https://user-images.githubusercontent.com/51204805/127555831-c7af3bdd-0974-4ab7-a603-01ecdbc0a369.png)
Может сделаем вью таким (речь про зеленый квадратик со скрина) - **{name} ({startTimespan})** ?
пример: **Side A: (00:00:00)**

**Comment by webgtx** [comment]
Я просто думал сделать такой пример:
  `chapters[0].duration + ' - ' + chapters[0].name`
  
  Идея в том что бы юзер выбирал отдельные песни по имени.
