### ISSUE TITLE
New folder structure

### ISSUE THREAD

**Issue by bubuntoid** [bubuntoid/YOVPS#18]
т.к. планировали в будущем использовать electron для десктопного приложения, предлагаю разделить структуру сурсов:

c:
```
└───src
    ├───BE
    │ 
    └───FE
```

на:
```
└───src
    ├───YOVPS.Core
    ├───YOVPS.Core.UnitTests
    ├───YOVPS.Core.Desktop (новый проект с электроном)
    ├───YOVPS.WebAPI
    └───YOVPS.WebApplication (старый FE)
```

но вообще чота так каша получается, имхо правильнее было бы тогда использовать разные репозитории -
* YOVPS
* YOVPS.Web
* YOVPS.Desktop
* YOVPS.Mobile
* etc

**Comment by bubuntoid** [comment]
@webgtx замечания/предложения/заметки?

**Comment by webgtx** [comment]
> @webgtx замечания/предложения/заметки?

Согласен, думаю сделаем на следущий мердж
