### ISSUE TITLE
Move index.html (+assets) to new folder

### ISSUE THREAD

**Issue by bubuntoid** [bubuntoid/YOVPS#9]
предлагаю папку назвать "dist"

> /dist means "distributable", the compiled code/libr

https://stackoverflow.com/a/22844164

**Comment by bubuntoid** [comment]
![image](https://user-images.githubusercontent.com/51204805/127649743-f2354dec-1fa3-405d-82a0-afbb71f535c3.png)
зеленое оставляем

**Comment by webgtx** [comment]
Я не против, **но тогда у нас не будет демо из гитхаба**, т.е что бы гитхаб мог хостить страницу - надо что бы файл **index.html** был в корне проекта.

**Comment by bubuntoid** [comment]
от туда в любом случае запросы на бек не идут + я захостил демку

**Comment by webgtx** [comment]
Окей тогда я думаю вопрос закрыт, в следушем коммите поменяю назвние.
